org: henningwold
app: flask-test
service: flask-test

frameworkVersion: '2'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "polly:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource:
        Fn::Join:
          - ""
          -
            - "arn:aws:s3:::"
            - Ref: AudioBucket
            - "/*"
functions:
  api:
    handler: wsgi_handler.handler
    environment:
      audioBucket:
        Ref: AudioBucket
      region: ${self:provider.region}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
resources:
  Resources:
    AudioBucket:
      Type: AWS::S3::Bucket
plugins:
  - serverless-wsgi
  - serverless-python-requirements
